version: '3.8'

services:
  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
    volumes:
      - qdrant_data:/qdrant/storage
    environment:
      - QDRANT__SERVICE__HTTP_PORT=6333
    restart: unless-stopped

  disaster-prep-app:
    build: .
    ports:
      - "8501:8501"
    depends_on:
      - qdrant
    environment:
      - QDRANT_URL=http://qdrant:6333
      - GROQ_API_KEY=${GROQ_API_KEY}
    volumes:
      - ./data:/app/data
    restart: unless-stopped

volumes:
  qdrant_data:
